name: Container Job

on:
  push:
    branches:
      main

env:
  test: value
  
jobs:
  regularjob:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ github.actor }}"
    - run: echo "${{ secrets.TEST_SECRET }}"
    - run: | 
        echo ${{ github.sha }}
        curl -sLX GET https://api.github.com/repos/${{ github.repository}}/commits/${{ github.sha }} \
          --header "Accept: application/vnd.github.v3+json" \
          --header "Authorization: Bearer ${{ secrets.github_token }}" | jq -c '.files[].filename'
    
  container:
    # runs-on: [self-hosted, azure]
    runs-on: ubuntu-latest
    container:
      # image: 'ubuntu:latest'
      image: 'ghcr.io/${{ github.repository }}:1'
      credentials:
         username: ${{ github.ref }}
         password: ${{ secrets.GITHUB_TOKEN }}
      env: 
        actor: ${{ github.actor }}

    steps:
    - uses: actions/checkout@main
    - run: ls
    - name: test1
      run: |
        echo "$actor"
    - name: test2
      run: echo "${{ github.actor }}"
    - name: test secret
      run: echo "${{ secrets.TEST_SECRET }}"
    - name: test env
      run: echo "${{ TEST }}"

        
